name: 'yuque-sync'
author: 'Liu Bowen'
description: 'sync post data from yuque webhook'
inputs:
  github-access-token:
    description: 'A repo scoped Github Personal Access Token'
    required: true
  out-dir:
    description: "Where should our documentations be place in",
    default: 'docs'
  out-file:
    description: 'As generated markdown file name'
    required: true
  content:
    description: 'As generated markdown file content',
    required: true
runs:
  using: 'node15'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
